# Generated by Django 4.2.4 on 2023-08-16 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vclass', '0004_student_date_of_birth_student_mobile_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
