# Generated by Django 4.2.4 on 2023-08-17 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vclass', '0005_student_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='profile_pic',
        ),
    ]
