# Generated by Django 4.2.4 on 2023-08-17 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vclass', '0007_course_course_decription_course_course_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course_decription',
            new_name='course_description',
        ),
    ]
