# Generated by Django 4.2.4 on 2023-08-17 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vclass', '0008_rename_course_decription_course_course_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_id',
            field=models.TextField(null=True),
        ),
    ]
