# Generated by Django 4.2.4 on 2023-08-17 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vclass', '0010_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='address',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='course_taken',
            field=models.TextField(null=True),
        ),
    ]
